-- 1. Create the 'posts' table
CREATE TABLE posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    tag TEXT NOT NULL,
    author TEXT NOT NULL,
    views INT DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Create the 'replies' table
CREATE TABLE replies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT REFERENCES posts(id) ON DELETE CASCADE,
    author TEXT NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Enable Row Level Security (RLS) to protect your database
ALTER TABLE posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE replies ENABLE ROW LEVEL SECURITY;

-- 4. Create policies to allow public READ access (everyone can see the posts/replies)
CREATE POLICY "Allow public read access for posts" ON posts FOR SELECT USING (true);
CREATE POLICY "Allow public read access for replies" ON replies FOR SELECT USING (true);

-- 5. Create policies to allow public INSERT access (anyone can submit a post/reply)
-- Note: In a real production app, you might want to require authentication, 
-- but for this open community board, we allow anonymous inserts.
CREATE POLICY "Allow public insert for posts" ON posts FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public insert for replies" ON replies FOR INSERT WITH CHECK (true);

-- 6. Create a policy to allow public UPDATE access (so we can increment the view count)
CREATE POLICY "Allow public update for post views" ON posts FOR UPDATE USING (true);
